In [25]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('./data/meal_order_detail.xlsx', sheet_name=0)

In [3]:
data.shape

(2779, 19)

In [4]:
data.head()

,detail_id,order_id,dishes_id,logicprn_name,parent_class_name,dishes_name,itemis_add,counts,amounts,cost,place_order_time,discount_amt,discount_reason,kick_back,add_inprice,add_info,bar_code,picture_file,emp_id
0,2956,417,610062,NaN,NaN,蒜蓉生蚝,0,1,49,NaN,2016-08-01 11:05:36,NaN,NaN,NaN,0,NaN,NaN,caipu/104001.jpg,1442
1,2958,417,609957,NaN,NaN,蒙古烤羊腿\r\n\r\n\r\n,0,1,48,NaN,2016-08-01 11:07:07,NaN,NaN,NaN,0,NaN,NaN,caipu/202003.jpg,1442
2,2961,417,609950,NaN,NaN,大蒜苋菜,0,1,30,NaN,2016-08-01 11:07:40,NaN,NaN,NaN,0,NaN,NaN,caipu/303001.jpg,1442
3,2966,417,610038,NaN,NaN,芝麻烤紫菜,0,1,25,NaN,2016-08-01 11:11:11,NaN,NaN,NaN,0,NaN,NaN,caipu/105002.jpg,1442
4,2968,417,610003,NaN,NaN,蒜香包,0,1,13,NaN,2016-08-01 11:11:30,NaN,NaN,NaN,0,NaN,NaN,caipu/503002.jpg,1442

In [14]:
data['date'] = [i.date() for i in pd.to_datetime(data['place_order_time'])]
data[['date', 'counts', 'amounts']].head()

         date  counts  amounts
0  2016-08-01       1       49
1  2016-08-01       1       48
2  2016-08-01       1       30
3  2016-08-01       1       25
4  2016-08-01       1       13

In [17]:
data_grouped = data[['date', 'counts', 'amounts']].groupby('date')

In [18]:
data_grouped.size()

date
2016-08-01    217
2016-08-02    138
2016-08-03    157
2016-08-04    144
2016-08-05    193
2016-08-06    706
2016-08-07    696
2016-08-08    160
2016-08-09    146
2016-08-10    222
dtype: int64

In [19]:
day_mean = data_grouped.agg({'amounts': 'mean'})

In [21]:
day_mean

              amounts
date
2016-08-01  43.161290
2016-08-02  44.384058
2016-08-03  43.885350
2016-08-04  52.423611
2016-08-05  44.927461
2016-08-06  45.562323
2016-08-07  44.979885
2016-08-08  40.825000
2016-08-09  49.006849
2016-08-10  46.085586

In [22]:
day_median = data_grouped.agg({'amounts': 'median'})

In [24]:
day_median

            amounts
date
2016-08-01       33
2016-08-02       35
2016-08-03       38
2016-08-04       39
2016-08-05       37
2016-08-06       35
2016-08-07       35
2016-08-08       34
2016-08-09       38
2016-08-10       35

In [28]:
data_grouped[['counts']].apply(np.sum)

            counts
date
2016-08-01     233
2016-08-02     151
2016-08-03     192
2016-08-04     169
2016-08-05     224
2016-08-06     793
2016-08-07     761
2016-08-08     171
2016-08-09     167
2016-08-10     227