# 文件的读取与写入

当使用 Pandas 做数据分析的时，需要读取事先准备好的数据集，这是做数据分析的第一步。Panda 提供了多种读取数据的方法：

`read_csv()` 用于读取文本文件

`read_excel()` 用于读取文本文件

`read_json()` 用于读取 json 文件
   
`read_sql()` 读取 sql 语句

**通用流程**
1. 导入库 import pandas as pd
2. 找到文件所在位置（绝对路径 = 全称）（相对路径 = 和程序在同一个文件夹中的路径的简称）
3. 变量名 = pd.读写操作方法（文件路径，具体的筛选条件，……）

# CSV文件读取

CSV 又称逗号分隔值文件，是一种简单的文件格式，以特定的结构来排列表格数据。 CSV 文件能够以纯文本形式存储表格数据，比如电子表格、数据库文件，并具有数据交换的通用格式。CSV 文件会在 Excel 文件中被打开，其行和列都定义了标准的数据格式。

将 CSV 中的数据转换为 DataFrame 对象是非常便捷的。和一般文件读写不一样，它不需要你做打开文件、读取文件、关闭文件等操作。相反，您只需要一行代码就可以完成上述所有步骤，并将数据存储在 DataFrame 中。


下面进行实例演示，源数据如下： 
<img src="images/20220424113515.png">

In [11]:
# 导入pandas库
import pandas as pd

In [12]:
# 查看版本
pd.__version__

'1.0.3'

In [15]:
# 读取 csv 文件，相对路径
df = pd.read_csv('./data/my_csv.csv')
df

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2022/1/1
1     3    b   3.4  banana  2022/1/2
2     6    c   2.5  orange  2022/1/5
3     5    d   3.2   grape  2022/1/7

In [18]:
import os

# 通过 os 动态获取绝对路径
print(os.getcwd())    # 获取当前工作路径
print(os.path.join(os.getcwd(), 'data/my_csv.csv'))

/Users/godfather/OneDrive/python数据分析与展示/代码/Python数据分析与展示/第三章 Pandas数据分析工具
/Users/godfather/OneDrive/python数据分析与展示/代码/Python数据分析与展示/第三章 Pandas数据分析工具/data/my_csv.csv

In [19]:
pd.read_csv(os.path.join(os.getcwd(), 'data/my_csv.csv'))

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2022/1/1
1     3    b   3.4  banana  2022/1/2
2     6    c   2.5  orange  2022/1/5
3     5    d   3.2   grape  2022/1/7

**方法详细说明**

`pandas.read_csv(filepath_or_buffer, sep=_NoDefault.no_default, delimiter=None, header='infer', names=_NoDefault.no_default, index_col=None, usecols=None, squeeze=None, prefix=_NoDefault.no_default, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=None, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, cache_dates=True, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, encoding_errors='strict', dialect=None, error_bad_lines=None, warn_bad_lines=None, on_bad_lines=None, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None, storage_options=None)[source]`

## 基本参数

1. `filepath_or_buffer`：数据输入的路径：可以是文件路径、可以是URL，也可以是实现read方法的任意对象。这个参数，就是我们输入的第一个参数。

2. `sep`: 读取csv文件时指定的分隔符，默认为逗号。注意："csv文件的分隔符" 和 "我们读取csv文件时指定的分隔符" 一定要一致。

In [21]:
pd.read_csv('./data/students_step.csv')

  id|name|address|gender|birthday
0         1|name1|地球村|女|2004/11/2
1          2|name2|月亮星|女|2003/8/7
2         3|name3|艾尔星|女|2004/11/2
3        4|name4|克哈星|男|2003/10/11
4         5|name5|查尔星|男|2002/6/12
5        6|name6|塔桑尼斯|男|2002/2/12

In [23]:
pd.read_csv('./data/students_step.csv', sep='|')

   id   name address gender    birthday
0   1  name1     地球村      女   2004/11/2
1   2  name2     月亮星      女    2003/8/7
2   3  name3     艾尔星      女   2004/11/2
3   4  name4     克哈星      男  2003/10/11
4   5  name5     查尔星      男   2002/6/12
5   6  name6    塔桑尼斯      男   2002/2/12

3. `header`:用作列名的行号，以及数据的开头。默认行为是推断列名：如果没有传递任何名称，则该行为与header=0相同，并且从文件的第一行推断列名，如果显式传递列名，则该行为与header=None相同。显式传递header=0以替换现有名称。标题可以是整数列表，指定列上多索引的行位置，例如[0,1,3]。未指定的中间行将被跳过（例如，本例中跳过2行）。请注意，如果skip_blank_lines=True，此参数将忽略注释行和空行，因此header=0表示数据的第一行，而不是文件的第一行。
4. `names`:当names没被赋值时，header会变成0，即选取数据文件的第一行作为列名；当 names 被赋值，header 没被赋值时，那么header会变成None。如果都赋值，就会实现两个参数的组合功能。

1) names没有被赋值，header也没有被赋值

In [24]:
# 这种情况下，header为0，即选取文件的第一行作为表头
pd.read_csv('./data/my_csv.csv')

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2022/1/1
1     3    b   3.4  banana  2022/1/2
2     6    c   2.5  orange  2022/1/5
3     5    d   3.2   grape  2022/1/7

2) names 没有被赋值，header 被赋值

In [25]:
# 不指定names，指定header为1，则选取第二行当做表头，第二行下面为数据
pd.read_csv('./data/my_csv.csv', header=1)

   2  a  1.4   apple  2022/1/1
0  3  b  3.4  banana  2022/1/2
1  6  c  2.5  orange  2022/1/5
2  5  d  3.2   grape  2022/1/7

3) names 被赋值，header 没有被赋值

In [26]:
pd.read_csv('./data/my_csv.csv', names=['编号', '姓名', '大小', '类别', '日期'])

     编号    姓名    大小      类别        日期
0  col1  col2  col3    col4      col5
1     2     a   1.4   apple  2022/1/1
2     3     b   3.4  banana  2022/1/2
3     6     c   2.5  orange  2022/1/5
4     5     d   3.2   grape  2022/1/7

可以看到，names适用于没有表头的情况，指定names没有指定header，那么header相当于None。
一般来说，读取文件的时候会有一个表头，一般默认是第一行，但是有的文件中是没有表头的，那么这个时候就可以通过names手动指定、或者生成表头，而文件里面的数据则全部是内容。所以这里id、name、address、date也当成是一条记录了，本来它是表头的，但是我们指定了names，所以它就变成数据了，表头是我们在names里面指定的。

4) names 和 header 都被赋值

In [30]:
pd.read_csv('./data/my_csv.csv',
           names=['编号', '姓名', '大小', '类别', '日期'],
           header=0)

   编号 姓名   大小      类别        日期
0   2  a  1.4   apple  2022/1/1
1   3  b  3.4  banana  2022/1/2
2   6  c  2.5  orange  2022/1/5
3   5  d  3.2   grape  2022/1/7

这个时候，相当于先不看names，只看header，header为0代表先把第一行当做表头，下面的当成数据；然后再把表头用names给替换掉。

> 所以 names 和 header 的使用场景主要如下：
>> - csv文件有表头并且是第一行，那么 names 和 header 都无需指定;
>> - csv文件有表头、但表头不是第一行，可能从下面几行开始才是真正的表头和数据，这个时候指定 header 即可;
>> - csv文件没有表头，全部是纯数据，那么我们可以通过 names 手动生成表头;
>> - csv文件有表头、但是这个表头你不想用，这个时候同时指定 names 和 header。先用 header 选出表头和数据，然后再用 names 将表头替换掉，就等价于将数据读取进来之后再对列名进行rename；

5. `index_col`：我们在读取文件之后所得到的 DataFrame 的索引默认是0、1、2……，我们可以通过set_index设定索引，但是也可以在读取的时候就指定某列为索引。

In [37]:
pd.read_csv('./data/my_csv.csv', index_col='col5')

          col1 col2  col3    col4
col5
2022/1/1     2    a   1.4   apple
2022/1/2     3    b   3.4  banana
2022/1/5     6    c   2.5  orange
2022/1/7     5    d   3.2   apple

这里，我们在读取的时候指定了name列作为索引；
此外，除了指定单个列，还可以指定多列作为索引，比如["id", "name"]。同时，我们除了可以输入列名外，还可以输入列对应的索引。比如："id"、"name"、"address"、"date"对应的索引就分别是0、1、2、3。

In [39]:
pd.read_csv('./data/my_csv.csv', index_col=['col4', 'col5'])

                 col1 col2  col3
col4   col5
apple  2022/1/1     2    a   1.4
banana 2022/1/2     3    b   3.4
orange 2022/1/5     6    c   2.5
apple  2022/1/7     5    d   3.2

6. `skiprows`：表示过滤行，想过滤掉哪些行，就写在一个列表里面传递给 skiprows 即可。注意的是：这里是先过滤，然后再确定表头

In [41]:
pd.read_csv('./data/my_csv.csv', skiprows=[0, 3])

   2  a  1.4   apple  2022/1/1
0  3  b  3.4  banana  2022/1/2
1  5  d  3.2   apple  2022/1/7

7. `nrows`：设置一次性读入的文件行数，在读入大文件时很有用，比如 16G 内存的PC无法容纳几百 G 的大文件

In [42]:
pd.read_csv('./data/my_csv.csv', nrows=3)

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2022/1/1
1     3    b   3.4  banana  2022/1/2
2     6    c   2.5  orange  2022/1/5

**时间处理相关的参数**

8. `parse_dates`：指定某些列为时间类型，这个参数一般搭配date_parser使用

9. `date_parser`：是用来配合parse_dates参数的，因为有的列虽然是日期，但没办法直接转化，需要我们指定一个解析格式

In [44]:
df = pd.read_csv('./data/my_csv.csv')
df

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2022/1/1
1     3    b   3.4  banana  2022/1/2
2     6    c   2.5  orange  2022/1/5
3     5    d   3.2   apple  2022/1/7

In [47]:
df = pd.read_csv('./data/my_csv.csv', parse_dates=['col5'])
df

   col1 col2  col3    col4       col5
0     2    a   1.4   apple 2022-01-01
1     3    b   3.4  banana 2022-01-02
2     6    c   2.5  orange 2022-01-05
3     5    d   3.2   apple 2022-01-07

In [48]:
pd.read_csv('./data/my_csv_年月日.csv')

   col1 col2  col3    col4       col5
0     2    a   1.4   apple  2022年1月1日
1     3    b   3.4  banana  2022年1月2日
2     6    c   2.5  orange  2022年1月5日
3     5    d   3.2   apple  2022年1月7日

In [51]:
pd.read_csv('./data/my_csv_年月日.csv', parse_dates=['col5'])

   col1 col2  col3    col4       col5
0     2    a   1.4   apple  2022年1月1日
1     3    b   3.4  banana  2022年1月2日
2     6    c   2.5  orange  2022年1月5日
3     5    d   3.2   apple  2022年1月7日

In [56]:
from datetime import datetime

df = pd.read_csv('./data/my_csv_年月日.csv',
                 parse_dates=['col5'],
                 date_parser=lambda x: datetime.strptime(x, '%Y年%m月%d日'))
df

   col1 col2  col3    col4       col5
0     2    a   1.4   apple 2022-01-01
1     3    b   3.4  banana 2022-01-02
2     6    c   2.5  orange 2022-01-05
3     5    d   3.2   apple 2022-01-07

**分块读入相关参数**

10. `iterator`：迭代器, iterator 为 bool 类型，默认为 False。如果为 True，那么返回一个 TextFileReader 对象，以便逐块处理文件。这个在文件很大、内存无法容纳所有数据文件时，可以分批读入，依次处理。

In [62]:
chunk = pd.read_csv('./data/my_csv.csv', iterator=True)
chunk

In [63]:
chunk.get_chunk(2)

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2022/1/1
1     3    b   3.4  banana  2022/1/2

In [64]:
# 文件还剩下两行，但是我们指定读取100，那么也不会报错，不够指定的行数，那么有多少返回多少
# 但是在读取完毕之后，再读的话就会报错了
chunk.get_chunk(100)

   col1 col2  col3    col4      col5
2     6    c   2.5  orange  2022/1/5
3     5    d   3.2   apple  2022/1/7

11. `chunksize`：整型，默认为 None，设置文件块的大小

In [65]:
chunk = pd.read_csv('./data/my_csv.csv', chunksize=2)

In [66]:
chunk

In [67]:
chunk.get_chunk()

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2022/1/1
1     3    b   3.4  banana  2022/1/2

In [68]:
chunk.get_chunk()

   col1 col2  col3    col4      col5
2     6    c   2.5  orange  2022/1/5
3     5    d   3.2   apple  2022/1/7

> 以上便是pandas的read_csv函数中绝大部分参数了，同时其中的部分参数也适用于读取其它类型的文件。
其实在读取csv文件时所使用的参数不多，很多参数平常我们都不会用到的，不过不妨碍我们了解一下，因为在某些特定的场景下它们是可以很方便地帮我们解决一些问题的。个人感觉分块读取这个参数最近在工作中提高了很大的效率。
上面列到的read_csv函数中的参数并不是全部，有几个还没有介绍到。
其它的读取文件的方法大体类似，可自行查阅