# Series数据类型

Series 结构，也称 Series 序列，是 Pandas 常用的数据结构之一，它是一种类似于一维数组的结构，由一组数据值（value）和一组标签组成，其中标签与数据值具有对应关系。

标签不必是唯一的，但必须是可哈希类型。该对象既支持基于整数的索引，也支持基于标签的索引，并提供了许多方法来执行涉及索引的操作。ndarray的统计方法已被覆盖，以自动排除缺失的数据（目前表示为NaN）

Series 可以保存任何数据类型，比如整数、字符串、浮点数、Python 对象等，它的标签默认为整数，从 0 开始依次递增。Series 的结构图，如下所示：

<img src="images/15400SM1-0.gif">

通过标签我们可以更加直观地查看数据所在的索引位置。

## 数据结构Series创建

`pd.Series(data=None, index=None, dtype=None, name=None, copy=False)`
- data 	输入的数据，可以是列表、常量、ndarray 数组等,如果是字典,则保持参数顺序
- index 索引值,必须是可散列的(不可变数据类型（str，bytes和数值类型）)，并且与数据具有相同的长度,允许使用非唯一索引值。如果未提供，将默认为RangeIndex（0，1，2，…，n）
- dtype 输出系列的数据类型。如果未指定，将从数据中推断
- name 为Series定义一个名称
- copy 	表示对 data 进行拷贝，默认为 False,仅影响Series和ndarray数组

In [2]:
import pandas as pd

In [3]:
# 一个最简单的series
series = pd.Series([2,4,5,7,3], index=['a','b','c','d','e'])
# 默认的索引是0到4
series

a    2
b    4
c    5
d    7
e    3
dtype: int64

- <b>通过 index 和 values 属性取得对应的标签和值</b>

In [4]:
series.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [5]:
series.values

array([2, 4, 5, 7, 3])

# DataFrame数据类型

DataFrame 是 Pandas 的重要数据结构之一，也是在使用 Pandas 进行数据分析过程中最常用的结构之一，可以这么说，掌握了 DataFrame 的用法，你就拥有了学习数据分析的基本能力。

### 认识DataFrame结构
 
DataFrame 一个表格型的数据结构，既有行标签（index），又有列标签（columns），它也被称异构数据表，所谓异构，指的是表格中每列的数据类型可以不同，比如可以是字符串、整型或者浮点型等。其结构图示意图，如下所示：

<img src="images/154931A54-0.gif">

表格中展示了某个销售团队个人信息和绩效评级（rating）的相关数据。数据以行和列形式来表示，其中每一列表示一个属性，而每一行表示一个条目的信息。

下表展示了上述表格中每一列标签所描述数据的数据类型，如下所示：

<img src="images/20220407223504.png" />

DataFrame 的每一列数据都可以看成一个 Series 结构，只不过，DataFrame 为每列数据值增加了一个列标签。因此 DataFrame 其实是从 Series 的基础上演变而来,并且他们有相同的标签,在数据分析任务中 DataFrame 的应用非常广泛，因为它描述数据的更为清晰、直观。

通过示例对  DataFrame 结构做进一步讲解。 下面展示了一张学生评分表，如下所示：
<img src="images/20220407230833.png">

同 Series 一样，DataFrame 自带行标签索引，默认为“隐式索引”即从 0 开始依次递增，行标签与 DataFrame 中的数据项一一对应。上述表格的行标签从 0 到 3，共记录了 4 条数据（图中将行标签省略）。当然你也可以用“显式索引”的方式来设置行标签。

下面对 DataFrame 数据结构的特点做简单地总结，如下所示：

- DataFrame 每一列的标签值允许使用不同的数据类型；
- DataFrame 是表格型的数据结构，具有行和列；
- DataFrame 中的每个数据值都可以被修改。
- DataFrame 结构的行数、列数允许增加或者删除；
- DataFrame 有两个方向的标签轴，分别是行标签和列标签；
- DataFrame 可以对行和列执行算术运算。

## 创建DataFrame对象

`pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)`

- data: 输入的数据，可以是 ndarray，series，list，dict，标量以及一个 DataFrame
- index: 行标签，如果没有传递 index 值，则默认行标签是 RangeIndex(0, 1, 2, …, n)，n 代表 data 的元素个数。
- columns: 列标签，如果没有传递 columns 值，则默认列标签是 RangeIndex(0, 1, 2, …, n)。
- dtype: 要强制的数据类型。只允许使用一种数据类型。如果没有，自行推断
- copy:  从输入复制数据。对于dict数据，copy=True,重新复制一份。对于DataFrame或ndarray输入，类似于copy=False,使用的是试图

**从字典创建一个DataFrame**

需要键（key）和值（value）来定义一个字典

In [9]:
# 首先产生一个叫gdp的字典
gdp = {"country": ["United States", "China", "Japan", "Germany", "United Kingdom"],
       "capital": ["Washington, D.C.", "Beijing", "Tokyo", "Berlin", "London"],
       "population": [323, 1389, 127, 83, 66],
       "gdp": [19.42, 11.8, 4.84, 3.42, 2.5],
       "continent": ["North America", "Asia", "Asia", "Europe", "Europe"]}

In [10]:
gdp_df = pd.DataFrame(gdp)
gdp_df

          country           capital  population    gdp      continent
0   United States  Washington, D.C.         323  19.42  North America
1           China           Beijing        1389  11.80           Asia
2           Japan             Tokyo         127   4.84           Asia
3         Germany            Berlin          83   3.42         Europe
4  United Kingdom            London          66   2.50         Europe

In [11]:
# 可以通过 index 选项添加自定义的行标签(label)
# 使用 columns 选项可以选择列的顺序
gdp_df = pd.DataFrame(gdp,
                      columns = ["country", "capital", "gdp", "continent", "population"],
                      index = ["us", "cn", "jp", "de", "uk"])
gdp_df

           country           capital    gdp      continent  population
us   United States  Washington, D.C.  19.42  North America         323
cn           China           Beijing  11.80           Asia        1389
jp           Japan             Tokyo   4.84           Asia         127
de         Germany            Berlin   3.42         Europe          83
uk  United Kingdom            London   2.50         Europe          66

**练习1**

如图创建DataFrame(4*4, 值为0-100的随机整数)

In [73]:
import numpy as np

df1 = pd.DataFrame(np.random.randint(100, size=(4, 4)),
                   columns=['a', 'b', 'c', 'd'],
                   index=['one', 'two', 'three', 'four'])
df1

        a   b   c   d
one    99  56  64  50
two    10   8  71  66
three  84   8  23  35
four    7  45   1  34

**修改行和列的标签**

In [12]:
# 也可以使用 index 和 columns 直接修改
gdp_df.index = ["US", "CN", "JP", "DE", "UK"]
gdp_df.columns = ["Country", "Capital", "GDP", "Continent", "Population"]
gdp_df

           Country           Capital    GDP      Continent  Population
US   United States  Washington, D.C.  19.42  North America         323
CN           China           Beijing  11.80           Asia        1389
JP           Japan             Tokyo   4.84           Asia         127
DE         Germany            Berlin   3.42         Europe          83
UK  United Kingdom            London   2.50         Europe          66

**增加一列数据**

In [13]:
# 增加 rank 列，表示他们的GDP处在前5位
gdp_df["Rank"] = "Top5 GDP"
# 增加国土面积变量,以百万公里计（数据来源：http://data.worldbank.org/）
gdp_df["Area"] = [9.15, 9.38, 0.37, 0.35, 0.24]
gdp_df

,Country,Capital,GDP,Continent,Population,Rank,Area
US,United States,"Washington, D.C.",19.42,North America,323,Top5 GDP,9.15
CN,China,Beijing,11.80,Asia,1389,Top5 GDP,9.38
JP,Japan,Tokyo,4.84,Asia,127,Top5 GDP,0.37
DE,Germany,Berlin,3.42,Europe,83,Top5 GDP,0.35
UK,United Kingdom,London,2.50,Europe,66,Top5 GDP,0.24

**调用属性和方法**

In [14]:
# 查看索引index
gdp_df.index

Index(['US', 'CN', 'JP', 'DE', 'UK'], dtype='object')

In [15]:
# 查看列名
gdp_df.columns

Index(['Country', 'Capital', 'GDP', 'Continent', 'Population', 'Rank', 'Area'], dtype='object')

In [16]:
# 查看数据
gdp_df.values

array([['United States', 'Washington, D.C.', 19.42, 'North America', 323,
        'Top5 GDP', 9.15],
       ['China', 'Beijing', 11.8, 'Asia', 1389, 'Top5 GDP', 9.38],
       ['Japan', 'Tokyo', 4.84, 'Asia', 127, 'Top5 GDP', 0.37],
       ['Germany', 'Berlin', 3.42, 'Europe', 83, 'Top5 GDP', 0.35],
       ['United Kingdom', 'London', 2.5, 'Europe', 66, 'Top5 GDP', 0.24]],
      dtype=object)

In [18]:
# 查看shape
gdp_df.shape

(5, 7)

In [19]:
# 均值计算
gdp_df.mean()

GDP             8.396
Population    397.600
Area            3.898
dtype: float64

## 数据的选择

- 我们可以使用`[[]]`来选择需要的列（如果只是用`[]`则产生一个series）
- 使用`[]`来选取需要的行
- 使用`loc`和`iloc`方法，选择行和列
- 使用布尔索引筛选数据

### `[[]]`来选取列

In [20]:
# 使用变量名加[[]]选取列
gdp_df[["Country"]]

           Country
US   United States
CN           China
JP           Japan
DE         Germany
UK  United Kingdom

In [22]:
# 可以同时选取多列
gdp_df[['Country', 'GDP']]

           Country    GDP
US   United States  19.42
CN           China  11.80
JP           Japan   4.84
DE         Germany   3.42
UK  United Kingdom   2.50

In [23]:
# 如果只是用[]则产生series
gdp_df["Country"]

US     United States
CN             China
JP             Japan
DE           Germany
UK    United Kingdom
Name: Country, dtype: object

In [24]:
# 使用句点符号也能获取某一列的Series
gdp_df.Country

US     United States
CN             China
JP             Japan
DE           Germany
UK    United Kingdom
Name: Country, dtype: object

### `[]`选取行

In [25]:
# 行选取和2d数组类似
gdp_df[2:5]   # 终索引是不被包括的

           Country Capital   GDP Continent  Population      Rank  Area
JP           Japan   Tokyo  4.84      Asia         127  Top5 GDP  0.37
DE         Germany  Berlin  3.42    Europe          83  Top5 GDP  0.35
UK  United Kingdom  London  2.50    Europe          66  Top5 GDP  0.24

### loc方法

- 是一种基于行标签和列标签选取数据的方法
- 可以选取特定行或列，也可以同时指定所需要的行与列
- 和二维numpy array的格式非常类似

In [29]:
# 在上面例子中，我们使用行索引选取行，能不能使用行标签实现选取呢？
# loc方法正是基于标签选取数据的方法
gdp_df.loc[['JP','DE']]

    Country Capital   GDP Continent  Population      Rank  Area
JP    Japan   Tokyo  4.84      Asia         127  Top5 GDP  0.37
DE  Germany  Berlin  3.42    Europe          83  Top5 GDP  0.35

In [30]:
# 添加列标签
gdp_df.loc[['JP', 'DE'], ['Country', 'GDP', 'Continent']]

    Country   GDP Continent
JP    Japan  4.84      Asia
DE  Germany  3.42    Europe

In [31]:
# 选取所有的行，我们可以使用:来表示选取所有的行
gdp_df.loc[:, ['Country', 'GDP', 'Continent']]

           Country    GDP      Continent
US   United States  19.42  North America
CN           China  11.80           Asia
JP           Japan   4.84           Asia
DE         Germany   3.42         Europe
UK  United Kingdom   2.50         Europe

### iloc方法

- 和 `loc` 方法不同的地方是，`iloc` 是基于行列索引进行数据选择而不是标签
- 具体使用方法和 `loc` 类似，用行/列索引代替标签

In [33]:
# gdp_df.loc[['JP','DE']]
gdp_df.iloc[[2, 3]]

    Country Capital   GDP Continent  Population      Rank  Area
JP    Japan   Tokyo  4.84      Asia         127  Top5 GDP  0.37
DE  Germany  Berlin  3.42    Europe          83  Top5 GDP  0.35

In [34]:
# gdp_df.loc[:, ['Country', 'GDP', 'Continent']]
gdp_df.iloc[:, [0, 2, 3]]

           Country    GDP      Continent
US   United States  19.42  North America
CN           China  11.80           Asia
JP           Japan   4.84           Asia
DE         Germany   3.42         Europe
UK  United Kingdom   2.50         Europe

### 使用布尔索引(boolean Indexing)筛选数据

- 我们可以使用pandas series来获取一个boolean series
- 布尔索引的使用和二维numpy array类似
- 可以结合`[]`或者`loc`一起使用

In [36]:
# 选出亚洲国家
gdp_df[gdp_df.Continent == 'Asia']

   Country  Capital    GDP Continent  Population      Rank  Area
CN   China  Beijing  11.80      Asia        1389  Top5 GDP  9.38
JP   Japan    Tokyo   4.84      Asia         127  Top5 GDP  0.37

In [37]:
gdp_df.loc[gdp_df.Continent == 'Asia']

   Country  Capital    GDP Continent  Population      Rank  Area
CN   China  Beijing  11.80      Asia        1389  Top5 GDP  9.38
JP   Japan    Tokyo   4.84      Asia         127  Top5 GDP  0.37

In [38]:
# 选出gdp大于3兆亿美元的欧洲国家
gdp_df[(gdp_df.Continent == 'Europe') & (gdp_df.GDP > 3)]

    Country Capital   GDP Continent  Population      Rank  Area
DE  Germany  Berlin  3.42    Europe          83  Top5 GDP  0.35

**练习2**

通过索引得到以下值

1. 索引得到b，c列的所有值
2. 索引得到第三第四行的数据
3. 索引得到大于50的值,不符合的赋值-1

In [74]:
df1.loc[:, ['b', 'c']]

        b   c
one    56  64
two     8  71
three   8  23
four   45   1

In [75]:
df1.iloc[[2, 3], :]

        a   b   c   d
three  84   8  23  35
four    7  45   1  34

In [76]:
df1>50

           a      b      c      d
one     True   True   True  False
two    False  False   True   True
three   True  False  False  False
four   False  False  False  False

In [77]:
df1[df1<50]=-1

In [78]:
df1

        a   b   c   d
one    99  56  64  50
two    -1  -1  71  66
three  84  -1  -1  -1
four   -1  -1  -1  -1

**练习3**

1. 选出亚洲或者北美洲的国家记录 (提示：使用 isin 方法)
2. 选出gdp大于4兆亿美元的国家

In [40]:
gdp_df[gdp_df.Continent.isin(['Asia', 'North America'])]

,Country,Capital,GDP,Continent,Population,Rank,Area
US,United States,"Washington, D.C.",19.42,North America,323,Top5 GDP,9.15
CN,China,Beijing,11.80,Asia,1389,Top5 GDP,9.38
JP,Japan,Tokyo,4.84,Asia,127,Top5 GDP,0.37

In [41]:
gdp_df[gdp_df.GDP > 4]

,Country,Capital,GDP,Continent,Population,Rank,Area
US,United States,"Washington, D.C.",19.42,North America,323,Top5 GDP,9.15
CN,China,Beijing,11.80,Asia,1389,Top5 GDP,9.38
JP,Japan,Tokyo,4.84,Asia,127,Top5 GDP,0.37

## 常用基本函数

### `head` 和 `tail`

In [42]:
df = pd.read_csv('./data/table.csv')

In [43]:
df.head()

  School Class    ID Gender   Address  Height  Weight  Math Physics
0    S_1   C_1  1101      M  street_1     173      63  34.0      A+
1    S_1   C_1  1102      F  street_2     192      73  32.5      B+
2    S_1   C_1  1103      M  street_2     186      82  87.2      B+
3    S_1   C_1  1104      F  street_2     167      81  80.4      B-
4    S_1   C_1  1105      F  street_4     159      64  84.8      B+

In [44]:
df.tail()

   School Class    ID Gender   Address  Height  Weight  Math Physics
30    S_2   C_4  2401      F  street_2     192      62  45.3       A
31    S_2   C_4  2402      M  street_7     166      82  48.7       B
32    S_2   C_4  2403      F  street_6     158      60  59.7      B+
33    S_2   C_4  2404      F  street_2     160      84  67.7       B
34    S_2   C_4  2405      F  street_6     193      54  47.6       B

**可以指定n行**

In [45]:
df.head(3)

  School Class    ID Gender   Address  Height  Weight  Math Physics
0    S_1   C_1  1101      M  street_1     173      63  34.0      A+
1    S_1   C_1  1102      F  street_2     192      73  32.5      B+
2    S_1   C_1  1103      M  street_2     186      82  87.2      B+

### `unique` 和 `nunique`

**`nunique` 显示有多少个唯一值**

In [46]:
df['Physics'].nunique()

7

**`unique`显示所有的唯一值**

In [47]:
df['Physics'].unique()

array(['A+', 'B+', 'B-', 'A-', 'B', 'A', 'C'], dtype=object)

### `count` 和 `value_counts`

**`count`返回非缺失值元素个数**

In [48]:
df['Physics'].count()

35

**`value_counts`返回每个元素有多少个**

In [50]:
df['Physics'].value_counts()

B+    9
B     8
B-    6
A     4
A+    3
A-    3
C     2
Name: Physics, dtype: int64

### `describe` 和 `info`

**`describe`默认统计数值型数据的各个统计量**

In [51]:
df.describe()

               ID      Height      Weight       Math
count    35.00000   35.000000   35.000000  35.000000
mean   1803.00000  174.142857   74.657143  61.351429
std     536.87741   13.541098   12.895377  19.915164
min    1101.00000  155.000000   53.000000  31.500000
25%    1204.50000  161.000000   63.000000  47.400000
50%    2103.00000  173.000000   74.000000  61.700000
75%    2301.50000  187.500000   82.000000  77.100000
max    2405.00000  195.000000  100.000000  97.000000

**对于非数值类型也可以用`describe()`**

In [53]:
df['Physics'].describe()

count     35
unique     7
top       B+
freq       9
Name: Physics, dtype: object

**`info`函数返回有哪些列、有多少非缺失值、每列的类型**

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   School   35 non-null     object
 1   Class    35 non-null     object
 2   ID       35 non-null     int64
 3   Gender   35 non-null     object
 4   Address  35 non-null     object
 5   Height   35 non-null     int64
 6   Weight   35 non-null     int64
 7   Math     35 non-null     float64
 8   Physics  35 non-null     object
dtypes: float64(1), int64(3), object(5)
memory usage: 2.6+ KB

## 排序

### 索引排序

In [54]:
df.set_index('Math').head()   # set_index函数可以设置索引

     School Class    ID Gender   Address  Height  Weight Physics
Math
34.0    S_1   C_1  1101      M  street_1     173      63      A+
32.5    S_1   C_1  1102      F  street_2     192      73      B+
87.2    S_1   C_1  1103      M  street_2     186      82      B+
80.4    S_1   C_1  1104      F  street_2     167      81      B-
84.8    S_1   C_1  1105      F  street_4     159      64      B+

In [55]:
df.set_index('Math').sort_index().head()   # 可以设置ascending参数，默认是升序，True

     School Class    ID Gender   Address  Height  Weight Physics
Math
31.5    S_1   C_3  1301      M  street_4     161      68      B+
32.5    S_1   C_1  1102      F  street_2     192      73      B+
32.7    S_2   C_3  2302      M  street_5     171      88       A
33.8    S_1   C_2  1204      F  street_5     162      63       B
34.0    S_1   C_1  1101      M  street_1     173      63      A+

### 值排序

In [56]:
df.sort_values(by='Class').head()

   School Class    ID Gender   Address  Height  Weight  Math Physics
0     S_1   C_1  1101      M  street_1     173      63  34.0      A+
19    S_2   C_1  2105      M  street_4     170      81  34.2       A
18    S_2   C_1  2104      F  street_5     159      97  72.2      B+
16    S_2   C_1  2102      F  street_6     161      61  50.6      B+
15    S_2   C_1  2101      M  street_7     174      84  83.3       C

**多个值排序，即先对第一层排，在第一层相同的情况下对第二层排序**

In [57]:
df.sort_values(by=['Address', 'Height']).head()

   School Class    ID Gender   Address  Height  Weight  Math Physics
0     S_1   C_1  1101      M  street_1     173      63  34.0      A+
11    S_1   C_3  1302      F  street_1     175      57  87.7      A-
23    S_2   C_2  2204      M  street_1     175      74  47.2      B-
33    S_2   C_4  2404      F  street_2     160      84  67.7       B
3     S_1   C_1  1104      F  street_2     167      81  80.4      B-